### ISSUE TITLE
Consider removing the Gemfile.lock

### ISSUE THREAD

**Issue by Nakilon** [ruby/syntax_suggest#134]
It is a bad practice to have it in a library to require.
https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by schneems** [comment]
There’s zero runtime dependencies in this gem. The Gemfile is purely for dev. Is it causing you problems?

**Comment by AlexWayfer** [comment]
> There’s zero runtime dependencies in this gem. The Gemfile is purely for dev. Is it causing you problems?

It may cause if some dependency version has been yanked, new patch-version released, and `Gemfile.lock` will be unwanted updated just after `bundle install`.

Simple locks in `.gemspec` or `Gemfile` are always better than `.lock` files, until you have an application, not library.

But in dev-only case it's not so critical. But I've introduced an example.
