### ISSUE TITLE
[Documentation / README] Initial authors?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/syntax_suggest#176]
Hello,

Would it be possible to add:

a) who the original authors of this gem were

and

b) when this gem was created?

I thought that mame created it, but now reading on the webpage and how many people appear to have contributed, I am no longer sure. It may also help me if I know when syntax_suggest was created, so perhaps someone could add this very briefly, one or two sentences, into the main README? Thank you for reading.

**Comment by schneems** [comment]
> I thought that mame created it, but now reading on the webpage and how many people appear to have contributed, I am no longer sure. It may also help me if I know when syntax_suggest was created, so perhaps someone could add this very briefly, one or two sentences, into the main README? Thank you for reading.

As mentioned it's all in the git history which GitHub exposes. I'm the creator and primary maintainer. Nobu and HSBT have made minor PRs here and there. You're probably thinking of error_highlight gem https://github.com/ruby/error_highlight.
