### ISSUE TITLE
Clarify in readme how to use in ruby >=3.2

### ISSUE THREAD

**Issue by jjb** [ruby/syntax_suggest#201]
If using ruby 3.2, is there anything needed to be done to get this functionality?

**Comment by schneems** [comment]
I missed this issue coming in. Sorry about that.

> If using ruby 3.2, is there anything needed to be done to get this functionality?

Nope. It's on by default unless you're running with `RUBYOPT="--disable=syntax_suggest"` for some reason. Now some libraries might catch when a `SyntaxError` is thrown and display their own errors. Rspec (did) that. It should have been fixed here https://github.com/rspec/rspec-core/pull/3015#issuecomment-1503084201

Are you seeing a case where you're expecting it to fire, but it didn't?

**Comment by jjb** [comment]
> It's on by default 
> Are you seeing a case where you're expecting it to fire, but it didn't?

great! no, just checking if it needs to be required when using ruby 3.2. maybe a note near the top of the readme would be helpful.
